apiVersion: v1
kind: Secret
metadata:
  name: bookapi-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "qXzKkBTPDu7j78X"

  # Example:
  # password: {{ .Values.password | b64enc }}